Export types in package.json
Types are not exported in package.json file. When using new "bundler" option for moduleResolution field included in TypeScript V5, you will receive the following error:
error TS7016: Could not find a declaration file for module 'goober'. '.../node_modules/goober/dist/goober.modern.js' implicitly has an 'any' type.
  There are types at '.../node_modules/goober/goober.d.ts', but this result could not be resolved when respecting package.json "exports". The 'goober' library may need to update its package.json or typings.